### ISSUE TITLE
Timeout when turn on/off

### ISSUE THREAD

**Issue by maisun** [denisw160/homebridge-hlsmartcontrol#11]
Hi,
Thanks for the great plug-in!
I have tried to set it up and experienced some issue with timeouts - either when I try to turn on or off the lamp. I have adjusted timeout to 2 second without luck, and when there is timeout, the accessory in HomeKit becomes unresponsive. I also noticed the web interface of the device sometimes extremely slow, opening the page takes 30 seconds etc., does anybody have similar experience or my device is defective? Thank you in advance!

**Comment by denisw160** [comment]
Hi, 

is the SmartControl on the latest firmware? I had also some problems with the older versions and WiFi. With the current version is everything works and the reaction of the web ui is fast. 

Or is the WiFi signal strength to low? Can the Homebridge ping the SmartControl?

**Comment by maisun** [comment]
> Hi,
> 
> is the SmartControl on the latest firmware? I had also some problems with the older versions and WiFi. With the current version is everything works and the reaction of the web ui is fast.
> 
> Or is the WiFi signal strength to low? Can the Homebridge ping the SmartControl?

Thank you for your reply! What is your timeout setting and do you see any timeout error in log? Mine has hardware version 1.1B, software version V2.1.0. What about yours? I don’t think WiFi signal is the problem as it is just a few meter from my unifi access point.

**Comment by denisw160** [comment]
Yes, same version - hardware is 1.1B, software is V2.1.0. My timeout is 1000 (1 second). I see no errors in my Homebridge log.

**Comment by denisw160** [comment]
Is the problem still there?

**Comment by maisun** [comment]
> Is the problem still there?

After switching to Unifi the problem occurs much less and not disturbing anymore, so I guess it's because the device sits inside the cabinet.

**Comment by denisw160** [comment]
Then probably really the WiFi connection / signal strength/quality. I could not find any problems with the network in my tests today. In my case, the access point and the smart control are in the same room and not 10 meters apart. 

I would therefore close this issue.
